name: Dispatch Receiver

on: [repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: dispatch trigger
        if: github.event.action == "YOUR_EVENT_TYPE"
        run: |
          echo "repository_dispatch triggered"