name: Starter demo workflow

on:
  push:
    branches: [ SWN-300-github-actions ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Runs a single command using the runners shell
      - uses: actions/checkout@v4.0.0
      - name: demo workflow job
        run: echo "This is a demo workflow"